person:
  name: kobe
  age: 12
  boss: false
  birth: 2019/1/1
  maps:
    lastName: wade
  lists:
    - cat
    - dog
    - pig
  dog:
    name: liuliu
    age: 2
spring:
  http:
    encoding:
      enabled: true
      charset: utf-8
#debug: true
logging:
  level: debug
